### ISSUE TITLE
HOWTO

### ISSUE THREAD

**Issue by stasiek** [andriyko/rfdocs#6]
Can You please create a HOWTO with way of populating it with data?

**Comment by selurvedu** [comment]
:+1:
Even though I've made a few pull requests for this project, I couldn't get it to work after all. rfdocs.org is dead, so I'd like to run an instance for my own needs.

**Comment by andriyko** [comment]
@selurvedu , it is not clear what actually does not work and what did you try to do.
You can start from here:
https://docs.djangoproject.com/en/1.8/topics/install/#get-your-database-running
https://docs.djangoproject.com/en/1.8/intro/tutorial01/#database-setup

Then
`python manage.py migrate`
`python manage.py createsuperuser`
`python manage.py runserver`

**Comment by selurvedu** [comment]
I, of course, did that and it works. But I have no idea how to fill the database with RF docs information.

**Comment by andriyko** [comment]
I don't have free time right now to work on howto, but here is a quick demo:
![rfdocs_demo](https://cloud.githubusercontent.com/assets/719450/10553534/3f7ccf78-7464-11e5-95e8-0226b713dac3.gif)

And some bulk operation:
![rfdocs_demo2](https://cloud.githubusercontent.com/assets/719450/10553545/4d17bf94-7464-11e5-8f56-a5f8808389e0.gif)

**Comment by selurvedu** [comment]
@andriyko That was really helpful, I finally have a nonempty installaton. Not everything's clear yet, but this is much, much better than nothing. Thanks! :+1:
